name: Deploy SAM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Pyhton 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: List files in working directory
        run: ls -R eksamen_2023-main/eksamen_2023-main/kjell

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Build and deploy SAM
        run: |
          sam build -t eksamen_2023-main/eksamen_2023-main/kjell/template.yaml --use-container
          sam deploy --stack-name kandidat2005 --region eu-west-1 --s3-bucket kandidat2005bucket --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset --no-confirm-changeset